### ISSUE TITLE
Issues with flex and containers

### ISSUE THREAD

**Issue by Amy-Stalter** [Amy-Stalter/responsive-image-section#1]
Hello @muxlowc
I am having issues where my image in its container will not size down as my screen sizes change, and I can not figure out why. Any help would be appreciated.

Thanks!

**Comment by muxlowc** [comment]
hey @Amy-Stalter 

So for img-flex:
1) it should only be put onto the actual <img> tag  (ie `<img class="img-flex" src=.....`)
2) in your css, img-flex should only be "`img-flex { display: block; width: 100%)`"  (not in any media queries)
-
You're currently trying to use img-flex to make the image 50% on larger sizes, but you actually need to target the img's parent div (which you currently have the "img-flex" class on)

The quickest way to start fixing this is to rename your current "img-flex" class to something different like "photo" and add "img-flex" class to your <img> tag, and add the `<img class="img-flex" src=`.....> into the css.

That should get you in the right direction - let me know if this still doesn;t work :)

**Comment by Amy-Stalter** [comment]
I was wondering if you had any time to meet today to maybe go over this issue with me in person?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by muxlowc** [comment]
@Amy-Stalter I'm not at the school today, but I can meet tomorrow.

I have class from 8-11 and 12-3 in N210 if you want to swing by then

**Comment by Amy-Stalter** [comment]
Alright I will try my best to debug using the advice you provided. Hopefully I can get it working before class tomorrow, if not, would I be able to get help either before or during the class?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Amy-Stalter** [comment]
@muxlowc I was able to fix the problem! Thank you!
